// docs/SECURITY.md generator (concern #10 handoff; spec §10/§13; checklist 4.3).
//
// Builder-sustainable SECURITY.md — emit-only for v0.2 (co-authoring with Vibe Doc
// is v0.3). The point: a security policy file a builder can hand to a customer or
// auditor that says something defensible-by-reference. ASVS-cited graduating
// guidance, the locked Mermaid threat-model convention documented for diff
// stability, and honeytokens surfaced as a Pattern #13 RECOMMENDATION (not
// generated — Conflict 6 = A: honeytoken generation is permanently out of scope;
// crosses from audit into active security ops).
//
// Pure: returns the markdown string; the caller writes it to docs/SECURITY.md.

import fs from "node:fs";
import path from "node:path";
import { type Tier } from "../types.js";
import type { Finding } from "./findings.js";
import { TIER_ASVS_LABEL, TIER_THRESHOLDS } from "../scoring/weighted-score.js";
import { securityMdPath } from "./paths.js";

/** Per-tier ASVS verification target, cited verbatim in the doc. */
const TIER_ASVS_CITATION: Record<Tier, string> = {
  prototype: "No formal verification target — this is a prototype.",
  internal: "OWASP ASVS Level 1 (L1) — the baseline for internal tools.",
  "public-facing": "OWASP ASVS Level 2 (L2) — the standard for public-facing applications.",
  "customer-facing-saas":
    "OWASP ASVS Level 3 (L3) — the bar for customer-facing SaaS handling sensitive data.",
  regulated:
    "OWASP ASVS Level 3 (L3) plus NIST SSDF practices (PO, PS, PW, RV) and a published SBOM.",
};

/** The next tier up, for the graduating-guidance section. */
const NEXT_TIER: Record<Tier, Tier | null> = {
  prototype: "internal",
  internal: "public-facing",
  "public-facing": "customer-facing-saas",
  "customer-facing-saas": "regulated",
  regulated: null,
};

const TIER_LABEL: Record<Tier, string> = {
  prototype: "Prototype / hackathon",
  internal: "Internal tool",
  "public-facing": "Public-facing",
  "customer-facing-saas": "Customer-facing SaaS",
  regulated: "Regulated / enterprise",
};

export interface SecurityMdOptions {
  tier: Tier;
  /** Weighted score in [0,1] at last audit, when known. */
  score?: number;
  /** Findings to summarize (deduped). Counts drive the posture summary. */
  findings?: readonly Finding[];
  /** App / project name for the header. */
  appName?: string;
  /** ISO timestamp; defaults to now. */
  generatedAt?: string;
  /** Security contact for the disclosure section, when provided. */
  securityContact?: string;
}

function countBySeverity(findings: readonly Finding[]): Record<string, number> {
  const counts: Record<string, number> = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of findings) counts[f.severity_tier_adjusted] = (counts[f.severity_tier_adjusted] ?? 0) + 1;
  return counts;
}

/**
 * Generate the SECURITY.md content. Always cites ASVS for the tier — that's the
 * load-bearing claim ("regulated tier resolves to ASVS L3 + SSDF + SBOM, not
 * aspiration"). Honeytokens appear only as a recommendation in the complements
 * section, never as generated artifacts.
 */
export function generateSecurityMd(opts: SecurityMdOptions): string {
  const tier = opts.tier;
  const generatedAt = opts.generatedAt ?? new Date().toISOString();
  const appName = opts.appName ?? "this project";
  const findings = opts.findings ?? [];
  const counts = countBySeverity(findings);
  const out: string[] = [];

  // ─── Header ──────────────────────────────────────────────────────────────
  out.push("# Security policy");
  out.push("");
  out.push(`> Generated by Vibe Sec ${generatedAt}. Emit-only — edit freely; re-running regenerates.`);
  out.push("");
  out.push(
    `This document describes the security posture and verification target for ${appName}. ` +
      "It is a builder-sustainable starting point, not a certification.",
  );
  out.push("");

  // ─── Verification target (the ASVS citation — load-bearing) ───────────────
  out.push("## Verification target");
  out.push("");
  out.push(`**Tier:** ${TIER_LABEL[tier]} (${TIER_ASVS_LABEL[tier]})`);
  out.push("");
  out.push(`**Standards floor:** ${TIER_ASVS_CITATION[tier]}`);
  out.push("");
  out.push(
    "The tier-to-ASVS mapping comes from the " +
      "[OWASP Application Security Verification Standard](https://owasp.org/www-project-application-security-verification-standard/). " +
      "It is a known-quantity verification target you can hand to auditors and customers — " +
      "not numbers picked in a vacuum.",
  );
  out.push("");
  out.push(`**Pass bar at this tier:** weighted score ≥ ${(TIER_THRESHOLDS[tier] * 100).toFixed(0)}%.`);
  if (typeof opts.score === "number") {
    out.push("");
    out.push(`**Last measured score:** ${(opts.score * 100).toFixed(0)}%.`);
  }
  out.push("");

  // ─── Current posture ──────────────────────────────────────────────────────
  out.push("## Current posture");
  out.push("");
  if (findings.length === 0) {
    out.push("No findings recorded yet. Run `/vibe-sec:audit` to populate this section.");
  } else {
    out.push(
      `Last audit recorded **${findings.length}** finding(s): ` +
        `${counts.critical} critical, ${counts.high} high, ${counts.medium} medium, ${counts.low} low.`,
    );
    out.push("");
    out.push("See `docs/vibe-sec/audit-report.md` for the full four-band report.");
  }
  out.push("");

  // ─── Graduating guidance (ASVS-cited, next-tier story) ────────────────────
  out.push("## Graduating guidance");
  out.push("");
  const next = NEXT_TIER[tier];
  if (next) {
    out.push(
      `When ${appName} graduates to **${TIER_LABEL[next]}**, the verification target rises to ` +
        `**${TIER_ASVS_LABEL[next]}**: ${TIER_ASVS_CITATION[next]}`,
    );
    out.push("");
    out.push("What comes into scope at the next tier:");
    out.push("");
    out.push(...graduatingChecklist(next));
  } else {
    out.push(
      "This is the highest tier. Maintain ASVS L3, keep NIST SSDF practices current, " +
        "and publish an SBOM (Syft / CycloneDX) with each release.",
    );
  }
  out.push("");

  // ─── Threat model convention (documented for diff stability) ──────────────
  out.push("## Threat model");
  out.push("");
  out.push(
    "Generate the threat model with `/vibe-sec:threat-model`. It emits " +
      "`docs/vibe-sec/threat-model.md` (Mermaid-in-markdown) plus a " +
      "`.vibe-sec/state/threat-model.json` sidecar compatible with " +
      "[OWASP Threat Dragon](https://owasp.org/www-project-threat-dragon/).",
  );
  out.push("");
  out.push(
    "Mermaid DFD convention (locked for diff-friendly diagrams): " +
      "stadiums = external entities, rectangles = processes, cylinders = data stores, " +
      "hexagons = third-parties, subgraphs = trust boundaries.",
  );
  out.push("");

  // ─── Vulnerability disclosure ─────────────────────────────────────────────
  out.push("## Reporting a vulnerability");
  out.push("");
  if (opts.securityContact) {
    out.push(`Report security issues to **${opts.securityContact}**. We aim to acknowledge within 72 hours.`);
  } else {
    out.push(
      "Add a security contact here (email or a private disclosure form). " +
        "A public `SECURITY.md` with no contact is a missed signal to good-faith researchers.",
    );
  }
  out.push("");

  // ─── Pattern #13 complements (incl. honeytokens as a RECOMMENDATION) ──────
  out.push("## Recommended complements");
  out.push("");
  out.push(
    "Vibe Sec is the orchestration layer, not the whole stack. These tools catch classes " +
      "the in-house baseline does not:",
  );
  out.push("");
  out.push("- **Secret scanning + push protection** (GitHub, GitGuardian) — block secrets before they land.");
  out.push("- **Socket.dev / Snyk** — supply-chain novelty and deeper SCA.");
  out.push("- **Semgrep CE** — deep injection (A03) and crypto rules.");
  if (tier === "public-facing" || tier === "customer-facing-saas" || tier === "regulated") {
    out.push("- **Arcjet / platform WAF** — rate limiting and abuse protection for public endpoints.");
  }
  out.push(
    "- **Honeytokens / canaries** (Thinkst Canarytokens, AWS canary keys) — " +
      "_a recommendation, not a generated artifact._ Plant decoy credentials that page you the " +
      "moment they're used. This crosses from audit into active security ops, so Vibe Sec surfaces " +
      "it as guidance rather than generating tokens for you. Best fit from Public-facing up.",
  );
  out.push("");

  return out.join("\n");
}

/** The next-tier scope checklist for the graduating-guidance section. */
function graduatingChecklist(next: Tier): string[] {
  switch (next) {
    case "internal":
      return [
        "- Lockfile present + no `latest`/`*` floating pins.",
        "- `nosniff`, `X-Frame-Options`, `HttpOnly` cookies.",
        "- Full route inventory + admin role-gate audit.",
      ];
    case "public-facing":
      return [
        "- OWASP Top 10 survey + rate limiting on auth routes (mandatory).",
        "- Full security headers + a Content Security Policy.",
        "- Dependency CVE scanning + SHA-pinned third-party GitHub Actions.",
        "- Basic IDOR checks (high-confidence) + the authorization matrix.",
      ];
    case "customer-facing-saas":
      return [
        "- Mandatory tenant isolation — every Supabase table with RLS, Firestore rules locked.",
        "- PII inventory + LINDDUN privacy walk in the threat model.",
        "- Enforcing strict CSP + COOP/COEP; crypto/PII handling mandatory.",
        "- Typosquat + dependency-confusion checks.",
      ];
    case "regulated":
      return [
        "- No High/Critical in any concern (the hard gate).",
        "- NIST SSDF practices (PO, PS, PW, RV) + published SBOM (Syft / CycloneDX).",
        "- Policy-as-code authorization, audit logging, SAML/SSO.",
        "- Attack trees for the top-5 threats; pytm threat-model-as-code.",
      ];
    default:
      return [];
  }
}

/**
 * Generate + write docs/SECURITY.md. The wire `/vibe-sec:audit --security-md`
 * (or a posture flag) calls this. Creates the docs dir as needed. Returns the
 * written path.
 */
export function emitSecurityMd(
  projectRoot: string,
  opts: SecurityMdOptions,
): string {
  const content = generateSecurityMd(opts);
  const file = securityMdPath(projectRoot);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, "utf8");
  return file;
}

export { TIER_ASVS_CITATION, NEXT_TIER };
